### ISSUE TITLE
Tiny Scientists mod request

### ISSUE THREAD

**Issue by andriy-gerasika** [stellaris-mods/tiny-outliner#1]
Hello,
I like your series of "tidy-*" mods, thanks for making 'em. Can you please also make a mod tinyfying list of scientists: I employ like 14 scientists and am constantly reassigning them depending on what science is being researched, so I have to scroll like a lot, making tiny version of "leader" window would help

**Comment by folknor** [comment]
Something like this?
https://imgur.com/a/eV03B

Thoughts / suggestions on the design?

**Comment by folknor** [comment]
![thumb](https://user-images.githubusercontent.com/233791/36077813-932a49a4-0f6f-11e8-949a-d275d697fc31.png)

**Comment by andriy-gerasika** [comment]
design is very nice...

is it possible to increase height of this window to have same height as outliner (or fit the screen vertically):
http://www.gerixsoft.com/tmp/tiny-leaders.png
this is my band of scientists exploring the galaxy for research points

**Comment by folknor** [comment]
http://www.gerixsoft.com/tmp/tiny-leaders.png does not exist, I get "Page not found" (404).

**Comment by folknor** [comment]
https://github.com/stellaris-mods/tiny-leaders/releases/tag/20180212-r1

**Comment by folknor** [comment]
http://steamcommunity.com/sharedfiles/filedetails/?id=1299357479

**Comment by andriy-gerasika** [comment]
http://www.gerixsoft.com/tmp/stellaris/tiny-leaders.png

I am totally abusing scientists, after the galaxy will be explored they will be reallocated to assist research, so more vertical space for leader window/scientist column will be a plus

**Comment by folknor** [comment]
Hehe, yes that is a lot of scientists :-)

I understand what you want now.
I don't want to do touch this window, because then the addon will not be 100% compatible with the 1080p addon, and will be more incompatible with the addons in the workshop that change the UI color, for example.

It's very easy to make your own addon, just use the Stellaris launcher to create one, and in the mod folder, create a folder called interface/, and add a file like zandriy.gui in it.

In the file, you need to copy+paste the contents of Stellaris/interface/topbar_leaders_view.gui, and at the bottom there's a section that looks like this
```
		smoothListboxType = {
			name ="scientists_list"
			position = { x = 319 y = 113 }
			size = { x= 293 y = 516 }
			scrollbartype = "standardlistbox_slider"
			spacing = -4
		}
```

Here you can change the y-size. Try `y=100%`, that works sometimes. Sometimes it does not work, so then you need to use an exact size.

Then ingame in the console, you can type `reload zandriy.gui` and close+reopen the window to see the change.

Sometimes you need to reload both:
```
reload topbar_leaders_view.gui
reload zandriy.gui
```
But try to just reload your file first. Remember you can use arrow keys in the ingame console to repeat commands.

Good luck!
